#pragma once
#include <iostream>
#include <stdlib.h>
#include <stdio.h>
#include <string>
#include <fstream>
#include <thread>
#include <chrono>
#include <windows.h>
#include <vector>
#include "GL/glew.h"
#include <stdint.h>
#include <stdarg.h>
#include <math.h>
#include <assert.h>
#include <limits.h>
#include <time.h>
#include <vector>
#include <ctime>
#include <list>
#include <sstream>